[package]
name = "microbio"
version = "0.1.0"
authors = ["msi <mbsd@m0x.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mb-server = { path = "../mb-server" }
